version: '3.8'

services:
    db:
        image: postgres:14
        restart: always
        environment:
            POSTGRES_DB: t_caps_db
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
